name: CI Tests
on:
  workflow_dispatch:
  push:
    branches-ignore: [main, e2e]

concurrency:
  group: tests
  cancel-in-progress: true

jobs:

  api-tests:
    name: Run Test
    runs-on: ubuntu-latest
    env:
      DB_NAME: test
      DB_USER: dev1
      DB_PASS: pass1
    steps:
      - name: Checkout API Branch
        uses: actions/checkout@v2
        with:
          ref: 'dev'

      - name: Setup PostgreSQL
        run: |
          sudo service postgresql start
          sudo -u postgres psql -c "CREATE DATABASE ${{ env.DB_NAME }}"
          sudo -u postgres psql -c "CREATE USER ${{ env.DB_USER }} WITH ENCRYPTED PASSWORD '${{ env.DB_PASS }}'"
          sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE ${{ env.DB_NAME }} TO ${{ env.DB_USER }}"          

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
          cache: 'maven'

      - name: Run Unit + Integration Tests
        run: 'mvn clean install'

  # web-tests:
  #   name: Web Tests
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Extract branch name
  #       shell: bash
  #       run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
  #       id: extract_branch

  #     - name: Checkout feature branch
  #       uses: actions/checkout@v2
  #       with:
  #         ref: ${{ steps.extract_branch.outputs.branch }}

  #     - name: Setup Node
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: '14'
  #         cache: 'npm'
  #         cache-dependency-path: web/package-lock.json

  #     - name: Build
  #       working-directory: web
  #       run: npm ci

  #     - name: Run Tests
  #       working-directory: web
  #       run: npm run test