name: CI Tests
on:
  workflow_dispatch:
  push:
    branches-ignore: [main, e2e]

concurrency:
  group: tests
  cancel-in-progress: true

jobs:

  web-tests:
    name: Web Tests
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Checkout repository feature branch
        uses: actions/checkout@v2
        with:
          ref: ${{ steps.extract_branch.outputs.branch }}