name: Production
on:
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  deploy-vercel-production:
    if: github.event.pull_request.merged == true
    name: Vercel PRODUCTION
    runs-on: ubuntu-latest
<<<<<<< HEAD
<<<<<<< HEAD
=======
    needs: [create-pull-request]
>>>>>>> deploy to production only when pull request merged
=======
>>>>>>> removed deps on prod deploy
    environment:
      name: web PRODUCTION
      url: ${{ steps.deploy.outputs.preview-url }}
    outputs:
      preview-url: ${{ steps.deploy.outputs.preview-url }}
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract-branch
      - name: Checkout API Branch
        uses: actions/checkout@v2
        with:
          ref: ${{ steps.extract-branch.outputs.branch }}
      - name: "Deploy to vercel production"
        id: deploy
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          scope: ${{ secrets.VERCEL_ORG_ID }} 
          vercel-args: '--prod -b REACT_APP_API_URL=https://offguard.herokuapp.com'
      - name: Update vercel url in secrets
        uses: hmanzur/actions-set-secret@v2.0.0
        with:
          name: 'VERCEL_PRODUCTION_URL'
          value: ${{ steps.deploy.outputs.preview-url }}
          token: ${{ secrets.PAT }}

  deploy-heroku-production:
    if: github.event.pull_request.merged == true
    name: Heroku PRODUCTION
    runs-on: ubuntu-latest
<<<<<<< HEAD
<<<<<<< HEAD
=======
    needs: [create-pull-request]
>>>>>>> deploy to production only when pull request merged
=======
>>>>>>> removed deps on prod deploy
    environment:
      name: api PRODUCTION
      url: https://offguard.herokuapp.com
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract-branch
      - name: Checkout API Branch
        uses: actions/checkout@v2
        with:
          ref: ${{ steps.extract-branch.outputs.branch }}
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
          cache: 'maven'
      - name: Build Backend
        working-directory: ./api
        run: mvn clean install -DskipTests
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          appdir: api
          branch: ${{ steps.extract-branch.outputs.branch }}
        env:
          # note: "HD_" is needed to specify what to include in the deployed heroku app.
          #       However, it is only needed to differentiate from other environment variables.
          #       The "HD_" string will be stripped when the app starts. 
          #       Therefore you need to use "FRONTEND_URL" when accessing from inside the app.  
          HD_FRONTEND_URL: ${{ secrets.VERCEL_PRODUCTION_URL }}